// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/common/common.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// example global proto to share
type Something struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Something) Reset()         { *m = Something{} }
func (m *Something) String() string { return proto.CompactTextString(m) }
func (*Something) ProtoMessage()    {}
func (*Something) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fd65e70ac205ee9, []int{0}
}

func (m *Something) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Something.Unmarshal(m, b)
}
func (m *Something) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Something.Marshal(b, m, deterministic)
}
func (m *Something) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Something.Merge(m, src)
}
func (m *Something) XXX_Size() int {
	return xxx_messageInfo_Something.Size(m)
}
func (m *Something) XXX_DiscardUnknown() {
	xxx_messageInfo_Something.DiscardUnknown(m)
}

var xxx_messageInfo_Something proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Something)(nil), "bernardosecades.common.Something")
}

func init() {
	proto.RegisterFile("protobuf/common/common.proto", fileDescriptor_2fd65e70ac205ee9)
}

var fileDescriptor_2fd65e70ac205ee9 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0x52, 0x7a, 0x60, 0x61,
	0x21, 0xb1, 0xa4, 0xd4, 0xa2, 0xbc, 0xc4, 0xa2, 0x94, 0xfc, 0xe2, 0xd4, 0xe4, 0xc4, 0x94, 0xd4,
	0x62, 0x3d, 0x88, 0xac, 0x12, 0x37, 0x17, 0x67, 0x70, 0x7e, 0x6e, 0x6a, 0x49, 0x46, 0x66, 0x5e,
	0xba, 0x93, 0x69, 0x94, 0x71, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x12, 0x48, 0x56, 0x1f, 0x4d, 0x87,
	0x3e, 0xd8, 0x20, 0xfd, 0xf4, 0x7c, 0x7d, 0x34, 0x8b, 0x92, 0xd8, 0xc0, 0x02, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x67, 0x93, 0xc3, 0xf5, 0x82, 0x00, 0x00, 0x00,
}
